# Generated by Django 5.2.10 on 2026-08-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djn_db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jurorresponse",
            name="juror_prompt_version",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="jurorresponse",
            name="role_instruction",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="jurorresponse",
            name="role_instruction_version",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddConstraint(
            model_name="djnround",
            constraint=models.UniqueConstraint(
                fields=("run", "round_index"), name="uniq_run_roundindex"
            ),
        ),
        migrations.AddConstraint(
            model_name="jurorresponse",
            constraint=models.UniqueConstraint(
                fields=("round", "juror_id"), name="uniq_round_juror"
            ),
        ),
    ]
