# Generated by Django 5.2.10 on 2026-08-24 12:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("djn_db", "0002_jurorresponse_juror_prompt_version_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="djnround",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="jurorresponse",
            unique_together=set(),
        ),
    ]
