# Generated by Django 5.2.10 on 2026-08-24 16:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djn_db", "0003_alter_djnround_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BenchmarkTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=120, unique=True)),
                ("dataset", models.CharField(max_length=120)),
                ("split", models.CharField(default="test", max_length=40)),
                ("category", models.CharField(default="general", max_length=30)),
                ("prompt", models.TextField()),
                ("reference_answer_json", models.JSONField(blank=True, default=dict)),
                ("scorer", models.CharField(max_length=40)),
                ("scorer_version", models.CharField(max_length=40)),
                ("source_url", models.URLField(blank=True, default="")),
                ("license", models.CharField(blank=True, default="", max_length=120)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="EvaluationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("experiment_config_id", models.CharField(max_length=64)),
                ("scorer_version", models.CharField(max_length=40)),
                ("score", models.FloatField(blank=True, null=True)),
                ("correct", models.BooleanField(blank=True, null=True)),
                ("details_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="RunFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voter_session", models.CharField(max_length=64)),
                ("value", models.SmallIntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="modelrollingstat",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="djnround",
            name="handoff_cost_estimate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="djnround",
            name="handoff_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="djnround",
            name="handoff_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="djnround",
            name="handoff_latency_ms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="djnround",
            name="handoff_model_id",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="djnround",
            name="handoff_prompt_version",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="djnround",
            name="handoff_queue_ms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="djnround",
            name="handoff_schema_valid",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="djnround",
            name="handoff_schema_version",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="djnround",
            name="handoff_usage_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="djnround",
            name="judge_cost_estimate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="djnround",
            name="judge_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="djnround",
            name="judge_latency_ms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="djnround",
            name="judge_model_id",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="djnround",
            name="judge_output_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="djnround",
            name="judge_queue_ms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="djnround",
            name="judge_schema_valid",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="djnround",
            name="judge_usage_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="djnround",
            name="stop_reason",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="djnrun",
            name="benchmark_task_id",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="djnrun",
            name="capability_version",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="djnrun",
            name="clarifier_skipped",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="djnrun",
            name="confidence_policy_version",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="djnrun",
            name="consensus_confidence",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="djnrun",
            name="experiment_config_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="djnrun",
            name="experiment_config_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="djnrun",
            name="pre_run_calls_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="djnrun",
            name="prompt_versions_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="djnrun",
            name="raw_judge_confidence",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="djnrun",
            name="scorer_version",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="djnrun",
            name="selection_seed",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="djnrun",
            name="selection_trace_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="djnrun",
            name="selector_version",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="jurorresponse",
            name="cached_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jurorresponse",
            name="cost_currency",
            field=models.CharField(blank=True, default="USD", max_length=8),
        ),
        migrations.AddField(
            model_name="jurorresponse",
            name="price_version",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="jurorresponse",
            name="queue_ms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jurorresponse",
            name="retry_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="jurorresponse",
            name="token_total",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jurorresponse",
            name="usage_unavailable_reason",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="llmpool",
            name="capabilities_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="llmpool",
            name="capability_version",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="llmpool",
            name="health_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="llmpool",
            name="health_status",
            field=models.CharField(default="UNKNOWN", max_length=20),
        ),
        migrations.AddField(
            model_name="modelrollingstat",
            name="completed_total",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="modelrollingstat",
            name="disagreement_total",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="modelrollingstat",
            name="error_total",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="modelrollingstat",
            name="feedback_events_total",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="modelrollingstat",
            name="latency_sample_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="modelrollingstat",
            name="latency_sum_ms",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="modelrollingstat",
            name="majority_win_total",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="modelrollingstat",
            name="schema_valid_total",
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="modelrollingstat",
            constraint=models.UniqueConstraint(
                fields=("model", "category"), name="uniq_model_category_stat"
            ),
        ),
        migrations.AddField(
            model_name="evaluationresult",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluation_results",
                to="djn_db.djnrun",
            ),
        ),
        migrations.AddField(
            model_name="evaluationresult",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="results",
                to="djn_db.benchmarktask",
            ),
        ),
        migrations.AddField(
            model_name="runfeedback",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_records",
                to="djn_db.djnrun",
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluationresult",
            constraint=models.UniqueConstraint(
                fields=("task", "experiment_config_id"),
                name="uniq_task_experiment_result",
            ),
        ),
        migrations.AddConstraint(
            model_name="runfeedback",
            constraint=models.UniqueConstraint(
                fields=("run", "voter_session"), name="uniq_run_voter_feedback"
            ),
        ),
        migrations.AddConstraint(
            model_name="runfeedback",
            constraint=models.CheckConstraint(
                condition=models.Q(("value__in", [-1, 1])),
                name="feedback_value_up_or_down",
            ),
        ),
    ]
